
name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-windows-x64:
    runs-on: windows-2022
    strategy:
      matrix:
        arch:
          - amd64
          - amd64_x86

    steps:
      - uses: actions/checkout@v2

      - name: Add msbuild to PATH
        - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Build
        run: nmake /f Makefile.vc CFG=release-static RTLIBCFG=static OBJDIR=output

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.arch }}
          path: output/

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: sudo apt-get install libjpeg-dev libpng-dev libtiff-dev libgif-dev build-essential cmake

      - name: Build
        run: |
          mkdir output && cd output && cmake ../
          make
      
      - uses: actions/upload-artifact@v2
        with:
          name: linux
          path: output/
